name: Move card in project view when label updated
on: [issues, pull_request]
jobs:
  Move_Labeled_Card_On_Project_Board:
    runs-on: ubuntu-latest
    steps:
      - uses: takanabe/github-actions-automate-projects@v0.0.1
        if: github.event.action == 'labeled' && (github.event_name == 'issues' && github.event.issue.state == 'open' && contains(github.event.issue.labels.*.name, 'discovery')) || (github.event_name == 'pull_request' && github.event.pull_request.state == 'open' && contains(github.event.pull_request.labels.*.name, 'discovery'))
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS }}
          GITHUB_PROJECT_URL: https://github.com/orgs/github/projects/2
          GITHUB_PROJECT_COLUMN_NAME: Backlog
      - uses: takanabe/github-actions-automate-projects@v0.0.1
        if: github.event.action == 'labeled' && (github.event_name == 'issues' && github.event.issue.state == 'open' && contains(github.event.issue.labels.*.name, 'blocked')) || (github.event_name == 'pull_request' && github.event.pull_request.state == 'open' && contains(github.event.pull_request.labels.*.name, 'blocked'))
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS }}
          GITHUB_PROJECT_URL: https://github.com/orgs/github/projects/2
          GITHUB_PROJECT_COLUMN_NAME: On hold
      - uses: takanabe/github-actions-automate-projects@v0.0.1
        if: github.event.action == 'labeled' && (github.event_name == 'issues' && github.event.issue.state == 'open' && contains(github.event.issue.labels.*.name, 'code review')) || (github.event_name == 'pull_request' && github.event.pull_request.state == 'open' && contains(github.event.pull_request.labels.*.name, 'code review'))
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS }}
          GITHUB_PROJECT_URL: https://github.com/orgs/github/projects/2
          GITHUB_PROJECT_COLUMN_NAME: Code review
      - uses: takanabe/github-actions-automate-projects@v0.0.1
        if: github.event.action == 'labeled' && (github.event_name == 'issues' && github.event.issue.state == 'open' && contains(github.event.issue.labels.*.name, 'testing')) || (github.event_name == 'pull_request' && github.event.pull_request.state == 'open' && contains(github.event.pull_request.labels.*.name, 'testing'))
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS }}
          GITHUB_PROJECT_URL: https://github.com/orgs/github/projects/2
          GITHUB_PROJECT_COLUMN_NAME: Testing
      - uses: takanabe/github-actions-automate-projects@v0.0.1
        if: github.event.action == 'labeled' && (github.event_name == 'issues' && github.event.issue.state == 'open' && contains(github.event.issue.labels.*.name, 'Ready for merge')) || (github.event_name == 'pull_request' && github.event.pull_request.state == 'open' && contains(github.event.pull_request.labels.*.name, 'Ready for merge'))
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS }}
          GITHUB_PROJECT_URL: https://github.com/orgs/github/projects/2
          GITHUB_PROJECT_COLUMN_NAME: Ready for merge?
